### ISSUE TITLE
Proposal: Improve XdgIconLoaderEngine so it stores fallback icon names

### ISSUE THREAD

**Issue by PCMan** [lxqt/libqtxdg#108]
The problem:
QIcon can only has one icon name. When the icon does not exist in the current theme, it simply breaks.
The qtxdg library provides a method to improve this:
  QIcon XdgIcon::fromTheme(const QStringList& iconNames, const QIcon& fallback)
However, this find the fallback icon on QIcon creation only. When the icon theme changes, the previously stored icon name might become invalid in the new theme.

The proposed solution:
Storing the list of all icon names in XdgIconLoaderEngine.
Then when creating a new QIcon via XdgIcon::fromTheme(),  create a XdgIconLoaderEngine with a list of possible icon names, and then create QIcon using the ctor that accepts an icon engine instead.
 QIcon::QIcon(QIconEngine\* engine)

After theme change, clear the pixmap cache used by QIcon so all pixmaps need to be re-generated.
When a pixmap needs to be generated again, we have the full icon name list in the icon engine ,so we can pick the most suitable icon name from the list for the current theme.

@luis-pereira What do you think?
The selection of the most suitable icon name from the list is done when generating the pixmap for the first time rather than when creating the QIcon object. The other parts remain the same and require no changes.

**Comment by luis-pereira** [comment]
`QIconCacheGtkReader` use solved the performance issue.
