### ISSUE TITLE
XdgDesktopFileCache::getDefaultApp cache wrong behavior

### ISSUE THREAD

**Issue by jleclanche** [lxqt/libqtxdg#18]
Moving Razor-qt bug from: https://github.com/Razor-qt/razor-qt/issues/520

Assigning to @pvanek. If this isn't relevant anymore, just close.

**Comment by luis-pereira** [comment]
@jleclanche @pvanek Taking this.

**Comment by agaida** [comment]
@luis-pereira - is this bug still valid?

**Comment by luis-pereira** [comment]
`XdgDesktopFileCache` is deprecated. `XdgMimeApps` fixes this issue.
