### ISSUE TITLE
qtxdg links to private header of <system> qtxdgiconloader

### ISSUE THREAD

**Issue by damianatorrpm** [lxqt/libqtxdg#186]
1.) Compile qtxdg with local qt (not the one in /usr, but /opt/Qt5.12.2)
2.) link to local qtxdg
` /usr/bin/ld: /usr/lib64/libQt5XdgIconLoader.so.3: undefined reference to QIconLoader::instance()@Qt_5.12.1_PRIVATE_API
`
Why does linking to local install qtxdg (Qt5.12.2), try to load the system xdgiconloader library instead of the local one?

**Comment by agaida** [comment]
because it find it first

**Comment by damianatorrpm** [comment]
I understand that this is not a problem specific to lxqt, yet I think default behaviour should be for qt apps to look in Qt's path first
