### ISSUE TITLE
CMAKE_INSTALL_PREFIX not accounted for in libQt5XdgIconPlugin.so install

### ISSUE THREAD

**Issue by ralphkw1** [lxqt/libqtxdg#194]
Attempts to install into "/usr/lib64/qt5/plugins/iconengines/libQt5XdgIconPlugin.so" even though CMAKE_INSTALL_PREFIX is set to "\~/usr". In the same build libQt5XdgIconLoader.so installs correctly into "\~/usr/lib64/libQt5XdgIconLoader.so".

##### Expected Behavior
Install into "\~/usr/lib64/libQt5XdgIconPlugin.so".

##### Current Behavior
Attempts to install into "/usr/lib64/qt5/plugins/iconengines/libQt5XdgIconPlugin.so".

##### Possible Solution
Update lxqt/libqtxdg/src/xdgiconloader/plugin/CMakeLists.txt to account for CMAKE_INSTALL_PREFIX. I am attempting to do this myself and will update the issue if I can get it working (I am new to CMAKE).

##### Steps to Reproduce (for bugs)
1. mkdir build 
2. cd build
3. cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=/home/rwilliamson/usr ..
4. make
5. make install

CMake Error at src/xdgiconloader/plugin/cmake_install.cmake:55 (file):
  file INSTALL cannot copy file
  "/home/rwilliamson/build/lxqt/libqtxdg/build/src/xdgiconloader/plugin/libQt5XdgIconPlugin.so"
  to "/usr/lib64/qt5/plugins/iconengines/libQt5XdgIconPlugin.so".

##### Context
Building without installing into main system.

##### System Information
Fedora LXQT 30. Using Toolbox.
Qt 5.12.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.2.1 20190827 (Red Hat 9.2.1-1)) on "xcb" 
OS: Fedora 30 (Container Image) [linux version 5.3.6-200.fc30.x86_64]
* Distribution & Version: Head from git.
* Kernel: Linux 5.3.6-200.fc30.x86_64 x86_64
* Qt Version: 5.12.5
* cmake Version:  3.14.5
* lxqt-build-tools Version: Head from git.
* Package version: N/A

**Comment by palinek** [comment]
The libQt5XdgIconPlugin.so is installed into directory where your currently used Qt can find it (that can be queried by `qmake -query QT_INSTALL_PLUGINS`).
But you can override it by setting the cmake variable QTXDGX_ICONENGINEPLUGIN_INSTALL_PATH.
