### ISSUE TITLE
WARNING: libqtxdg needs recompilation with Qt 5.14.2

### ISSUE THREAD

**Issue by tsujan** [lxqt/libqtxdg#204]
After Qt 5.14.2 came to Arch, I saw crashes in screengrab. The cause was in libqtxdg. Recompilation of libqtxdg solved the problem.

Usually, there should be no need to recompile fundamental LXQt components when the third version number of Qt changes. This was an exception.

I close this issue immediately after opening it; just wanted to make distro package maintainers know about it.

P.S. I have the latest git LXQt but think that the latest release (which is very old, BTW) should be affected too.

**Comment by yan12125** [comment]
FYI, it's already done in Arch: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/libqtxdg&id=17a08ff55d363f20232768095c2ce01771acae83, and Arch has a list for such "exceptions" at https://git.archlinux.org/kde-build.git/tree/rebuild.list?h=qt.

**Comment by tsujan** [comment]
> FYI, it's already done in Arch

Thanks for the info! Good to know that Arch's LXQt isn't affected :)

I was worried about Arch because some of its packages are old, while Arch should support latest releases. For example. I'll release FeatherPad 0.13.2 in a week but the latest Arch package is still 0.11.1 https://aur.archlinux.org/packages/featherpad/ (fortunately, AUR's [featherpad-git](https://aur.archlinux.org/packages/featherpad-git/) still works but I would prefer a cmake compilation instead of qmake).

**Comment by yan12125** [comment]
Well, AUR is another story, you know...
