### ISSUE TITLE
Look into Qt "Fix double scaling of SVG icons on high DPI screens"

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/libqtxdg#224]
@tsujan You did some work in `ScalableEntry::pixmap()`.
Can you check if https://code.qt.io/cgit/qt/qtbase.git/commit/src/gui/image/qiconloader.cpp?id=d8ab719c0890195cfce0fb6d4c76b3664d6f3a9d applies to us ?

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* cmake Version:  
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
@luis-pereira 
After https://github.com/lxqt/libqtxdg/pull/203 (which may be seen as a workaround for a Qt bug), there is no problem with SVG+scaling in LXQt. An example with a ridiculous scale factor of 5:

![svg_icons](https://user-images.githubusercontent.com/981076/88829958-8efd4b00-d1e2-11ea-88c0-ca124eb21f69.png)

But it's good to see what Qt devs have done and whether it's relevant to our code. Thanks for the link! Will look into it as soon as I find the time.

**Comment by tsujan** [comment]
@luis-pereira 
The final result is the same but their fix is better than my workaround. So, I made a PR: https://github.com/lxqt/libqtxdg/pull/225
