### ISSUE TITLE
`xdg-utils` should use `qtxdg-mat` under LXQt

### ISSUE THREAD

**Issue by tsujan** [lxqt/libqtxdg#264]
This isn't a bug in LXQt but an urgent need.

Currently, `xdg-open` only uses `open_generic` under LXQt, causing troubles like https://github.com/lxqt/lxqt-panel/issues/1661.

@luis-pereira made `qtxdg-mat`. It should be used in `xdg-open` under LXQt.

**Comment by tsujan** [comment]
Also, you may want to take a look at https://github.com/lxqt/lxqt-panel/issues/1661#issuecomment-917721942

**Comment by luis-pereira** [comment]
@tsujan Real life get's in the way. But it's ready for testing, now.
Pls try the `enhance-lxqt-support` [branch](https://gitlab.freedesktop.org/luis-pereira/xdg-utils/-/commits/enhance-lxqt-support) at [my fork](https://gitlab.freedesktop.org/luis-pereira/xdg-utils/) from [upstream xdg-utils](https://gitlab.freedesktop.org/xdg/xdg-utils).

After positive feedback I will make a merge request.

**Comment by tsujan** [comment]
@luis-pereira 
Many thanks!

I applied your patch (https://gitlab.freedesktop.org/luis-pereira/xdg-utils/-/commit/d2adf5efdc259a63028f8d4f21569c1557b8cfff) to `xdg-utils` 1.1.3+19+g9816ebb. Everything seems OK; https://github.com/lxqt/lxqt-panel/issues/1661 isn't reproducible anymore.

I'll use it for a few days and report back.

**Comment by tsujan** [comment]
@stefonarch, could you also confirm that https://gitlab.freedesktop.org/luis-pereira/xdg-utils/-/commit/d2adf5efdc259a63028f8d4f21569c1557b8cfff fixes https://github.com/lxqt/lxqt-panel/issues/1661 without `~/.local/share/applications/defaults.list`?

**Comment by stefonarch** [comment]
Ok, looks like this filelight error doesn't show up anymore now. Will test for  some days.

**Comment by tsujan** [comment]
@luis-pereira
I haven't encountered any problem with your patch after three days.

**Comment by luis-pereira** [comment]
> I haven't encountered any problem with your patch after three days.

Nice.

**Comment by luis-pereira** [comment]
@stefonarch Do you have any feedback on this ?

**Comment by tsujan** [comment]
In case you also want to know what I see here after 17 days, it's the same as before: have encountered no problem.

**Comment by stefonarch** [comment]
Sorry thought I'd said it somewhere: no issues encountered all those days.

**Comment by stefonarch** [comment]
> After positive feedback I will make a merge request.

News about that?

**Comment by tsujan** [comment]
> News about that?

@luis-pereira made the merge request 5 months ago: https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/48. But apparently there's a problem ("Merge blocked: the source branch must be rebased onto the target branch.")

**Comment by luis-pereira** [comment]
@tsujan @stefonarch I will rebase after the weekend. There weren't any merge conflicts when I made the merge request.

**Comment by tsujan** [comment]
> There weren't any merge conflicts when I made the merge request.

I know; saw it only today.

**Comment by luis-pereira** [comment]
Rebased.

**Comment by yan12125** [comment]
Upstream xdg-utils seems no so active. I'm afraid the patch will not be merged soon. I uploaded https://aur.archlinux.org/packages/xdg-utils-lxqt, so users on Arch-like systems can use the patched version easily.

**Comment by tsujan** [comment]
> Upstream xdg-utils seems no so active.

Can't we explicitly request a review there?

**Comment by tsujan** [comment]
We're out of luck; the patch has a conflict again: https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/48

**Comment by luis-pereira** [comment]
Closed by commit https://gitlab.freedesktop.org/xdg/xdg-utils/-/commit/91c8d8088238369590397523e8a0dec3b27c9af2

**Comment by tsujan** [comment]
Very good news! Now `xdg-open` is reliable under LXQt, through and besides `qtxdg-mat` :)
