### ISSUE TITLE
Problem loading `/usr/share/pixmaps/` icons

### ISSUE THREAD

**Issue by isf63** [lxqt/libqtxdg#305]
I have `htop` installed and it provides `/usr/share/pixmaps/htop.png` for its icon. The .desktop file correctly has `Icon=htop` but the icon is never disaplyed.

##### Steps to Reproduce (for bugs)
1. Install `htop` 
2. Verify desktop file `/usr/share/applications/htop.desktop` is correct
3. Missing icon in PCManFM-Qt, application menus, and Runner
4. 

##### Context
This bug may affect other user applications

##### System Information
* Distribution & Version: Arch Linux
* Qt Version: 5.15.14, 6.7.1
* Package version: 4.0.0

**Comment by tsujan** [comment]
Not reproducible.

Actually, I tested more: Since `htop` has an icon in the the Breeze icon theme (which my theme inherits), I created an `htop1` desktop entry with `/usr/share/pixmaps/htop1.png` as its icon and put it inside `~/.local/share/applications/`. It was shown correctly in pcmanfm-qt, lxqt-runner and Fancy Menu.

**Comment by yan12125** [comment]
For the case of htop, `/usr/share/icons/hicolor/scalable/apps/htop.svg` is used, and Qt 6.7 cannot render it correctly: https://bugreports.qt.io/browse/QTBUG-123138

**Comment by stefonarch** [comment]
Here no issue too:
![immagine](https://github.com/lxqt/libqtxdg/assets/10681413/384a82f3-f81d-426a-bf35-d9f779a61433)

**Comment by stefonarch** [comment]
Only the icon in hicolor can't be rendered by lximage-qt:
```
$ locate htop|grep icon
/usr/share/icons/Papirus/16x16/apps/bashtop.svg
/usr/share/icons/Papirus/16x16/apps/htop.svg
/usr/share/icons/Papirus/22x22/apps/bashtop.svg
/usr/share/icons/Papirus/22x22/apps/htop.svg
/usr/share/icons/Papirus/24x24/apps/bashtop.svg
/usr/share/icons/Papirus/24x24/apps/htop.svg
/usr/share/icons/Papirus/32x32/apps/bashtop.svg
/usr/share/icons/Papirus/32x32/apps/htop.svg
/usr/share/icons/Papirus/48x48/apps/bashtop.svg
/usr/share/icons/Papirus/48x48/apps/htop.svg
/usr/share/icons/Papirus/64x64/apps/bashtop.svg
/usr/share/icons/Papirus/64x64/apps/htop.svg
/usr/share/icons/breeze/apps/48/htop.svg
/usr/share/icons/breeze-dark/apps/48/htop.svg
/usr/share/icons/hicolor/scalable/apps/htop.svg

**Comment by isf63** [comment]
I use `mate-icon-theme` icons. Indeed it is the `/hicolor/` icon that can't be rendered - `sudo mv /usr/share/icons/hicolor/scalable/apps/htop.svg{,.tmp}` and restarting Desktop, the `/pixmaps/` icon is found and displayed correctly.

**Comment by tsujan** [comment]
So, this was about a regression in Qt6, not about `/usr/share/pixmaps/`. @yan12125, thanks for the link!

I can confirm the regression because my Qt5-based image viewer shows `/usr/share/icons/hicolor/scalable/apps/htop.svg` correctly, while lximage-qt can't show it.
